### ISSUE TITLE
Not every log-in is successful

### ISSUE THREAD

**Issue by iostyle** [VNG-Zalo/ZaloSDK-Android-Demo#1]
Even with the demo

**Comment by liemvu** [comment]
Any error code / message?
Make sure the demo app is signed with provided debug.keystore.

**Comment by iostyle** [comment]
> Any error code / message?
> Make sure the demo app is signed with provided debug.keystore.


ActivityResult is OK. 
But no callback.

**Comment by liemvu** [comment]
Did you call method ZaloSDK.Instance.onActivityResult(...)? Some thing like this:
`protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        ZaloSDK.Instance.onActivityResult(this, requestCode, resultCode, data);
    }`

If you did call that method but still no callback, could you please send me the content of data.getExtras()?

**Comment by iostyle** [comment]
> Did you call method ZaloSDK.Instance.onActivityResult(...)? Some thing like this:
> `protected void onActivityResult(int requestCode, int resultCode, Intent data) { super.onActivityResult(requestCode, resultCode, data); ZaloSDK.Instance.onActivityResult(this, requestCode, resultCode, data); }`
> 
> If you did call that method but still no callback, could you please send me the content of data.getExtras()?

{"data":{"uid":6351843807829507551,"code":"uRppJvr8sqBzYhOiobU8LRE9ksAEMQvq_8R3Owvyb0Fgkwu-ktp8K8RIyWF6Diir_khI9OuqWXZdpkruh0VNJ_h8koB74xfRkSIxDA4XhY3C_SiJZpkWQCJvbqQr48nztOZIJuDj_N6XjF1_hZN35wJulHVZAVHtugt4H89ZzIJ8bBbYv4MqGAFue7A7Fzu2-k3YB9mUxJFPivGovKsK7QkbYJ_8IPGgkhVgUCNtE6J-8M4--XO1mT310CxS2NoeoC9aaUWHRfhDnZE-uHWZpRMdLCFdDN6UpeW2uIOjFgXfbq6j6W","gender":"other","phone":"","dob":"01\/01\/1980","socialId":"","display_name":"sky406910111"},"error":0,"errorMsg":""}

**Comment by iostyle** [comment]
> Did you call method ZaloSDK.Instance.onActivityResult(...)? Some thing like this:
> `protected void onActivityResult(int requestCode, int resultCode, Intent data) { super.onActivityResult(requestCode, resultCode, data); ZaloSDK.Instance.onActivityResult(this, requestCode, resultCode, data); }`
> 
> If you did call that method but still no callback, could you please send me the content of data.getExtras()?

{"data":{"uid":6351843807829507551,"code":"uRppJvr8sqBzYhOiobU8LRE9ksAEMQvq_8R3Owvyb0Fgkwu-ktp8K8RIyWF6Diir_khI9OuqWXZdpkruh0VNJ_h8koB74xfRkSIxDA4XhY3C_SiJZpkWQCJvbqQr48nztOZIJuDj_N6XjF1_hZN35wJulHVZAVHtugt4H89ZzIJ8bBbYv4MqGAFue7A7Fzu2-k3YB9mUxJFPivGovKsK7QkbYJ_8IPGgkhVgUCNtE6J-8M4--XO1mT310CxS2NoeoC9aaUWHRfhDnZE-uHWZpRMdLCFdDN6UpeW2uIOjFgXfbq6j6W","gender":"other","phone":"","dob":"01\/01\/1980","socialId":"","display_name":"sky406910111"},"error":0,"errorMsg":""}

**Comment by iostyle** [comment]
Doesn't look different

**Comment by iostyle** [comment]
Doesn't look any different

**Comment by liemvu** [comment]
> > Did you call method ZaloSDK.Instance.onActivityResult(...)? Some thing like this:
> > `protected void onActivityResult(int requestCode, int resultCode, Intent data) { super.onActivityResult(requestCode, resultCode, data); ZaloSDK.Instance.onActivityResult(this, requestCode, resultCode, data); }`
> > If you did call that method but still no callback, could you please send me the content of data.getExtras()?
> 
> {"data":{"uid":6351843807829507551,"code":"uRppJvr8sqBzYhOiobU8LRE9ksAEMQvq_8R3Owvyb0Fgkwu-ktp8K8RIyWF6Diir_khI9OuqWXZdpkruh0VNJ_h8koB74xfRkSIxDA4XhY3C_SiJZpkWQCJvbqQr48nztOZIJuDj_N6XjF1_hZN35wJulHVZAVHtugt4H89ZzIJ8bBbYv4MqGAFue7A7Fzu2-k3YB9mUxJFPivGovKsK7QkbYJ_8IPGgkhVgUCNtE6J-8M4--XO1mT310CxS2NoeoC9aaUWHRfhDnZE-uHWZpRMdLCFdDN6UpeW2uIOjFgXfbq6j6W","gender":"other","phone":"","dob":"01/01/1980","socialId":"","display_name":"sky406910111"},"error":0,"errorMsg":""}

This mean a successful login. Could you please send me your login code?

**Comment by iostyle** [comment]
> > > Did you call method ZaloSDK.Instance.onActivityResult(...)? Some thing like this:
> > > `protected void onActivityResult(int requestCode, int resultCode, Intent data) { super.onActivityResult(requestCode, resultCode, data); ZaloSDK.Instance.onActivityResult(this, requestCode, resultCode, data); }`
> > > If you did call that method but still no callback, could you please send me the content of data.getExtras()?
> > 
> > 
> > {"data":{"uid":6351843807829507551,"code":"uRppJvr8sqBzYhOiobU8LRE9ksAEMQvq_8R3Owvyb0Fgkwu-ktp8K8RIyWF6Diir_khI9OuqWXZdpkruh0VNJ_h8koB74xfRkSIxDA4XhY3C_SiJZpkWQCJvbqQr48nztOZIJuDj_N6XjF1_hZN35wJulHVZAVHtugt4H89ZzIJ8bBbYv4MqGAFue7A7Fzu2-k3YB9mUxJFPivGovKsK7QkbYJ_8IPGgkhVgUCNtE6J-8M4--XO1mT310CxS2NoeoC9aaUWHRfhDnZE-uHWZpRMdLCFdDN6UpeW2uIOjFgXfbq6j6W","gender":"other","phone":"","dob":"01/01/1980","socialId":"","display_name":"sky406910111"},"error":0,"errorMsg":""}
> 
> This mean a successful login. Could you please send me your login code?

What login code? Zalo Account?

**Comment by iostyle** [comment]
> > > Did you call method ZaloSDK.Instance.onActivityResult(...)? Some thing like this:
> > > `protected void onActivityResult(int requestCode, int resultCode, Intent data) { super.onActivityResult(requestCode, resultCode, data); ZaloSDK.Instance.onActivityResult(this, requestCode, resultCode, data); }`
> > > If you did call that method but still no callback, could you please send me the content of data.getExtras()?
> > 
> > 
> > {"data":{"uid":6351843807829507551,"code":"uRppJvr8sqBzYhOiobU8LRE9ksAEMQvq_8R3Owvyb0Fgkwu-ktp8K8RIyWF6Diir_khI9OuqWXZdpkruh0VNJ_h8koB74xfRkSIxDA4XhY3C_SiJZpkWQCJvbqQr48nztOZIJuDj_N6XjF1_hZN35wJulHVZAVHtugt4H89ZzIJ8bBbYv4MqGAFue7A7Fzu2-k3YB9mUxJFPivGovKsK7QkbYJ_8IPGgkhVgUCNtE6J-8M4--XO1mT310CxS2NoeoC9aaUWHRfhDnZE-uHWZpRMdLCFdDN6UpeW2uIOjFgXfbq6j6W","gender":"other","phone":"","dob":"01/01/1980","socialId":"","display_name":"sky406910111"},"error":0,"errorMsg":""}
> 
> This mean a successful login. Could you please send me your login code?

It's looks like successful, but no callback sometimes.

**Comment by iostyle** [comment]
I used this demo with my AppId, but not every login has callback.

**Comment by iostyle** [comment]
The demo error rate is 10 percent, and my project error rate is 50 percent.
I don't know what went wrong.

**Comment by liemvu** [comment]
In case of unsuccess login or user cancel, method onAuthenError of OAuthCompleteListener class will be called instead. You can override it to get the error code & message.

**Comment by iostyle** [comment]
If the login fails, neither onGetOAuthComplete nor onAuthenError is called

**Comment by liemvu** [comment]
Please define the listener as a class var instead of inline anonymous object. Some thing like [this](https://github.com/VNG-Zalo/ZaloSDK-Android-Demo/commit/69d76839753fd999f1aa6f4e267a7f1745aeb02b)

**Comment by iostyle** [comment]
I see. Thank you very much! 🤝
